import Mathlib.Tactic

import Mathlib.RingTheory.Ideal.Int
import Mathlib.RingTheory.Ideal.Prod
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Idempotents

/-!
# Exercises — RingTheory / Ideals and Quotients

For a commutative ring `R`, an ideal `I` is a subset closed under subtraction and multiplication
by arbitrary elements of `R`. Thus `a, b ∈ I` implies `a - b ∈ I`, and `r ∈ R`, `a ∈ I` implies
`r * a ∈ I`. The principal ideal `(a)` consists of the multiples of `a`; more generally,
`Ideal.span S` is the smallest ideal containing `S`.

The quotient ring `R ⧸ I` has cosets `a + I`, with `a + I = b + I` precisely when `a - b ∈ I`.
Quotienting by `I` makes every element of `I` zero. Kernels of ring homomorphisms are ideals, and
the first isomorphism theorem identifies `R ⧸ ker f` with `im f`. Ideal sums, products, and
intersections combine congruence conditions; the Chinese remainder theorem treats simultaneous
congruences for suitably related ideals.

Prove each statement yourself; the canonical proofs will live in
`Solutions/RingTheory/02Ideals.lean`. Do **not** commit your proofs into this file.
-/


namespace Exercises.RingTheory.Ideals

variable {R S : Type*} [CommRing R] [CommRing S]

/-! ## Potentially helpful results -/
section

-- Principal and generated ideals.
#check @Ideal.mem_span_range_iff_exists_fun
#check @Ideal.mem_span_pair
#check @Ideal.span_le
#check @Ideal.subset_span

-- Quotient rings and maps between them.
#check @Ideal.Quotient.eq_zero_iff_mem
#check @Ideal.Quotient.mk_eq_mk_iff_sub_mem
#check @Ideal.Quotient.mk_surjective
#check @RingHom.injective_iff_ker_eq_bot
#check @RingHom.lift_injective_of_ker_le_ideal
#check @Ideal.Quotient.lift_surjective_of_surjective
#check @RingEquiv.ofBijective

end


/-- **Question 1.**

The ideal generated by `6` and `15` is `(3)`.

Show each inclusion: `3` divides both generators, while `3 = -2 · 6 + 15`. -/
theorem q1_span_six_fifteen :
    Ideal.span ({(6 : ℤ), 15} : Set ℤ) = Ideal.span ({3} : Set ℤ) := by
  sorry


/-- **Question 2.**

A principal ideal generated by `a` consists exactly of the multiples of `a`.

Prove without using `Ideal.mem_span_singleton` or `Ideal.mem_span_singleton'`. -/
theorem q2_mem_span_singleton_iff {R : Type*} [CommRing R] (a x : R) :
    x ∈ Ideal.span ({a} : Set R) ↔ ∃ r : R, a * r = x := by
  sorry


/-- **Question 3.**

The principal ideal `(a)` is the smallest ideal containing `a`.

Prove without using `Ideal.span_singleton_le_iff_mem`. -/
theorem q3_span_singleton_le_iff {R : Type*} [CommRing R] (a : R) (I : Ideal R) :
    Ideal.span ({a} : Set R) ≤ I ↔ a ∈ I := by
  sorry


/-- **Question 4.**

In a domain, two principal ideals agree exactly when their nonzero generators differ by a unit.

Prove without using `Ideal.span_singleton_eq_span_singleton`. -/
theorem q4_span_singleton_eq_iff_associated {R : Type*} [CommRing R] [IsDomain R]
    (a b : R) (hb0 : b ≠ 0) :
    Ideal.span ({a} : Set R) = Ideal.span ({b} : Set R) ↔
      ∃ u : R, IsUnit u ∧ a = b * u := by
  sorry


/-- **Question 5.**

The image of an ideal under a ring homomorphism need not be an ideal. Prove this using the
image of the canonical diagonal map `ℤ → ℤ × ℤ`. -/
theorem q5_image_of_ideal_need_not_be_ideal :
    ¬ ∃ I : Ideal (ℤ × ℤ), ∀ x : ℤ × ℤ,
      x ∈ I ↔ ∃ n : ℤ, Int.castRingHom (ℤ × ℤ) n = x := by
  sorry


/-- **Question 6.**

The inverse image of an ideal along a ring homomorphism is an ideal of the source ring.

Construct that ideal directly, without using `Ideal.comap`. -/
theorem q6_exists_ideal_comap {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (J : Ideal S) :
    ∃ I : Ideal R, ∀ r : R, r ∈ I ↔ f r ∈ J := by
  sorry


/-- **Question 7.**

The quotient by the inverse image of an ideal embeds in the corresponding target quotient.

Prove without using `Ideal.quotientMap` or `Ideal.quotientMap_injective`. -/
theorem q7_quotient_comap_embeds_quotient {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (J : Ideal S) :
    ∃ g : R ⧸ Ideal.comap f J →+* S ⧸ J, Function.Injective g := by
  sorry


/-- **Question 8.**

The first isomorphism theorem identifies `R / ker f` with the range of `f`.

Prove without using `RingHom.quotientKerEquivRange` (or either
`RingHom.quotientKerEquivOfSurjective` or `RingHom.quotientKerEquivOfRightInverse`). -/
theorem q8_first_iso_ring (f : R →+* S) : Nonempty (R ⧸ RingHom.ker f ≃+* f.range) := by
  sorry


/-- **Question 9.**

The quotient by an ideal represents maps that send the ideal to zero: every such map factors
through the quotient.

Prove without using `Ideal.Quotient.lift`. -/
theorem q9_quotient_represents_maps_killing_ideal {R S : Type*} [CommRing R]
    [CommRing S] (I : Ideal R) (f : R →+* S) (hf : ∀ x : R, x ∈ I → f x = 0) :
    ∃ g : R ⧸ I →+* S, ∀ x : R, g (Ideal.Quotient.mk I x) = f x := by
  sorry


/-- **Question 10.**

Two idempotents generate an ideal that is itself generated by one idempotent. -/
theorem q10_two_idempotents_generate_idempotent_ideal {R : Type*} [CommRing R]
    (a b : R) (ha : IsIdempotentElem a) (hb : IsIdempotentElem b) :
    ∃ e : R, IsIdempotentElem e ∧ Ideal.span ({a, b} : Set R) = Ideal.span ({e} : Set R) := by
  sorry


/-- **Question 11.**

Coprime ideals have intersection equal to their product.

Prove without using `Ideal.mul_eq_inf_of_isCoprime` or `Ideal.mul_le_inf`. -/
theorem q11_coprime_inf_eq_mul {R : Type*} [CommRing R] (I J : Ideal R) (h : I + J = ⊤) :
    I ⊓ J = I * J := by
  sorry


/-- The canonical map to the quotient rings by the two ideals determined by an idempotent. -/
def idempotent_product_quotient_map {R : Type*} [CommRing R] (e : R) :
    R →+* (R ⧸ Ideal.span ({e} : Set R)) × R ⧸ Ideal.span ({1 - e} : Set R) :=
  (Ideal.Quotient.mk _).prod (Ideal.Quotient.mk _)


/-- **Question 12.**

For an idempotent `e`, the natural map to the two quotient rings by `(e)` and `(1 - e)` is both
injective and surjective.

Prove without using `AlgEquiv.prodQuotientOfIsIdempotentElem`. -/
theorem q12_idempotent_gives_product_decomposition {R : Type*} [CommRing R] (e : R)
    (he : IsIdempotentElem e) :
    Function.Injective (idempotent_product_quotient_map e) ∧
      Function.Surjective (idempotent_product_quotient_map e) := by
  sorry

end Exercises.RingTheory.Ideals
