import Mathlib.Tactic

import Mathlib.Algebra.Polynomial.Eval.Defs

import Mathlib.Order.Preorder.Finite
import Mathlib.RingTheory.Ideal.Int
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Ideal.Prod
import Mathlib.RingTheory.Ideal.Quotient.Operations

namespace Solutions.RingTheory.PrimeAndMaximalIdeals

variable {R : Type*} [CommRing R]


theorem q1_quotient_domain_iff_prime (I : Ideal R) : IsDomain (R ⧸ I) ↔ I.IsPrime := by
  constructor
  · intro hdomain
    refine ⟨?_, ?_⟩
    · intro htop
      -- If `I = ⊤`, then the quotient has `0 = 1`, contradicting that it is a domain.
      letI : Nontrivial (R ⧸ I) := hdomain.toNontrivial
      have hone : Ideal.Quotient.mk I (1 : R) = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (htop.symm ▸ Submodule.mem_top)
      have honezero : (1 : R ⧸ I) = 0 := by simpa only [map_one] using hone
      exact (one_ne_zero : (1 : R ⧸ I) ≠ 0) honezero
    · intro x y hxy
      -- A zero product in the quotient is exactly a product lying in `I`.
      have hzero : Ideal.Quotient.mk I x * Ideal.Quotient.mk I y = 0 := by
        rw [← map_mul, Ideal.Quotient.eq_zero_iff_mem]
        exact hxy
      rcases eq_zero_or_eq_zero_of_mul_eq_zero hzero with hx | hy
      · exact Or.inl (Ideal.Quotient.eq_zero_iff_mem.mp hx)
      · exact Or.inr (Ideal.Quotient.eq_zero_iff_mem.mp hy)
  · intro hprime
    -- Conversely, primality makes a zero product of residue classes force one factor to vanish.
    letI : Nontrivial (R ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr hprime.1
    letI : NoZeroDivisors (R ⧸ I) :=
      { eq_zero_or_eq_zero_of_mul_eq_zero := by
          intro a b hab
          refine Quotient.inductionOn₂' a b ?_ hab
          intro x y hxy
          exact (hprime.mem_or_mem (Ideal.Quotient.eq_zero_iff_mem.mp hxy)).elim
            (Or.inl ∘ Ideal.Quotient.eq_zero_iff_mem.mpr)
            (Or.inr ∘ Ideal.Quotient.eq_zero_iff_mem.mpr) }
    exact NoZeroDivisors.to_isDomain _


theorem q2_comap_prime {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
    (J : Ideal S) (hJ : J.IsPrime) : (Ideal.comap f J).IsPrime := by
  -- A product maps into `J` exactly when the product of its images does, so primality of `J`
  -- applies directly.
  refine ⟨by simpa using hJ.1, ?_⟩
  intro x y hxy
  have hxy_mem : f x * f y ∈ J := by simpa using hxy
  simpa using hJ.2 hxy_mem


theorem q3_quotient_field_iff_maximal (I : Ideal R) : I.IsMaximal ↔ IsField (R ⧸ I) := by
  constructor
  · intro hmax
    -- For a nonzero class `[x]`, the ideal generated by `I` and `x` strictly contains `I`.
    -- Maximality therefore writes `1 = yx + z` with `z ∈ I`; modulo `I`, `y` is an inverse of `[x]`.
    letI : Nontrivial (R ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr hmax.ne_top
    refine ⟨⟨0, 1, zero_ne_one⟩, mul_comm, ?_⟩
    intro a ha
    obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective a
    have hxnot : x ∉ I := by
      intro hxi
      exact ha (Ideal.Quotient.eq_zero_iff_mem.mpr hxi)
    have hone : (1 : R) ∈ I ⊔ Ideal.span {x} :=
      (Ideal.isMaximal_iff.mp hmax).2 (I ⊔ Ideal.span {x}) x le_sup_left hxnot
        (Submodule.mem_sup_right (Ideal.mem_span_singleton_self x))
    have hone' : (1 : R) ∈ Ideal.span {x} ⊔ I := by simpa [sup_comm] using hone
    obtain ⟨y, z, hz, hyz⟩ := Ideal.mem_span_singleton_sup.mp hone'
    refine ⟨Ideal.Quotient.mk I y, ?_⟩
    have hmz : Ideal.Quotient.mk I z = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr hz
    calc
      Ideal.Quotient.mk I x * Ideal.Quotient.mk I y = Ideal.Quotient.mk I (x * y) := by
        rw [map_mul]
      _ = Ideal.Quotient.mk I (y * x) := by rw [mul_comm]
      _ = Ideal.Quotient.mk I (y * x) + Ideal.Quotient.mk I z := by rw [hmz, add_zero]
      _ = Ideal.Quotient.mk I (y * x + z) := by rw [map_add]
      _ = 1 := by rw [hyz, map_one]
  · intro hfield
    -- Conversely, a proper ideal strictly containing `I` would make a nonzero residue class
    -- invertible, forcing `1` into that larger ideal.
    apply Ideal.isMaximal_iff.2
    constructor
    · intro htop
      rcases hfield.exists_pair_ne with ⟨⟨x⟩, ⟨y⟩, hxy⟩
      exact hxy (Ideal.Quotient.eq.2 (mul_one (x - y) ▸ I.mul_mem_left _ htop))
    · intro J x hIJ hxnI hxJ
      rcases hfield.mul_inv_cancel (mt Ideal.Quotient.eq_zero_iff_mem.1 hxnI) with ⟨⟨y⟩, hy⟩
      rw [← zero_add (1 : R), ← sub_self (x * y), sub_add]
      exact J.sub_mem (J.mul_mem_right _ hxJ) (hIJ (Ideal.Quotient.eq.1 hy))


theorem q4_maximal_prime (I : Ideal R) (hI : I.IsMaximal) : I.IsPrime := by
  -- A maximal ideal has a field quotient; a field has no zero divisors.
  apply (q1_quotient_domain_iff_prime I).mp
  exact ((q3_quotient_field_iff_maximal I).mp hI).isDomain


theorem q5_int_prime_maximal (p : ℕ) [Fact p.Prime] :
    Ideal.span ({(p : ℤ)} : Set ℤ) ≠ ⊤ ∧
    ∀ J : Ideal ℤ, Ideal.span ({(p : ℤ)} : Set ℤ) < J → J = ⊤ := by
  have hp : p.Prime := Fact.out
  refine ⟨?_, ?_⟩
  · -- p ≥ 2 is not a unit in ℤ; the ideal is proper.
    intro htop
    have hunit : IsUnit (p : ℤ) := Ideal.span_singleton_eq_top.mp htop
    exact hp.ne_one (by simpa [Int.isUnit_iff] using hunit)
  · intro J hJ
    -- Witness the strict containment: find x ∈ J with p ∤ x.
    have hJ_not_le_span : ¬ J ≤ Ideal.span ({(p : ℤ)} : Set ℤ) := not_le_of_gt hJ
    obtain ⟨x, hxJ, hpx_not_dvd⟩ := SetLike.not_le_iff_exists.mp hJ_not_le_span
    rw [Ideal.mem_span_singleton] at hpx_not_dvd
    -- gcd(p, x) divides p; primality forces gcd = 1 or gcd = p.
    have hgcd1 : Int.gcd (p : ℤ) x = 1 := by
      rcases hp.eq_one_or_self_of_dvd (Int.gcd (p : ℤ) x)
          (by exact_mod_cast Int.gcd_dvd_left (p : ℤ) x) with h | h
      · exact h
      -- gcd = p would mean p ∣ x, contradicting hpx_not_dvd.
      · exact absurd (h ▸ (by exact_mod_cast Int.gcd_dvd_right (p : ℤ) x)) hpx_not_dvd
    -- Bezout: gcdA·p + gcdB·x = 1; both terms lie in J, so 1 ∈ J.
    rw [Ideal.eq_top_iff_one]
    have hbez : Int.gcdA (p : ℤ) x * p + Int.gcdB (p : ℤ) x * x = 1 := by
      have h := Int.gcd_eq_gcd_ab (p : ℤ) x
      rw [show (Int.gcd (p : ℤ) x : ℤ) = 1 from by exact_mod_cast hgcd1] at h
      linarith [mul_comm (p : ℤ) (Int.gcdA (p : ℤ) x),
                mul_comm x (Int.gcdB (p : ℤ) x)]
    rw [← hbez]
    exact J.add_mem
      (J.mul_mem_left _ (hJ.le (Ideal.mem_span_singleton_self _)))
      (J.mul_mem_left _ hxJ)


theorem q6_zero_prime_not_maximal : (⊥ : Ideal ℤ).IsPrime ∧ ¬ (⊥ : Ideal ℤ).IsMaximal := by
  constructor
  · refine ⟨?_, ?_⟩
    · exact bot_ne_top
    · intro x y hxy
      rw [Submodule.mem_bot] at hxy ⊢
      exact eq_zero_or_eq_zero_of_mul_eq_zero hxy
  · intro hmax
    -- The nontrivial ideal `(2)` sits strictly between `(0)` and the whole ring.
    have hproper : (⊥ : Ideal ℤ) < Ideal.span ({(2 : ℤ)} : Set ℤ) := by
      refine lt_of_le_of_ne bot_le ?_
      intro h
      have htwo : (2 : ℤ) ∈ (⊥ : Ideal ℤ) := by
        rw [h]
        exact Ideal.mem_span_singleton_self 2
      norm_num [Submodule.mem_bot] at htwo
    have hnot_top : Ideal.span ({(2 : ℤ)} : Set ℤ) ≠ ⊤ := by
      intro htop
      have hunit : IsUnit (2 : ℤ) := Ideal.span_singleton_eq_top.mp htop
      norm_num [Int.isUnit_iff] at hunit
    exact hnot_top (hmax.1.2 _ hproper)


theorem q7_x_ideal_prime_not_maximal :
    (Ideal.span ({Polynomial.X} : Set (Polynomial ℤ))).IsPrime ∧
      ¬ (Ideal.span ({Polynomial.X} : Set (Polynomial ℤ))).IsMaximal := by
  constructor
  · exact (Ideal.span_singleton_prime Polynomial.X_ne_zero).mpr Polynomial.prime_X
  · intro h
    -- Adjoin the constant polynomial `2`; the larger ideal would be the whole ring only if
    -- `2` divided `1` after taking constant coefficients.
    rw [Ideal.isMaximal_iff] at h
    let J : Ideal (Polynomial ℤ) := Ideal.span ({Polynomial.X, Polynomial.C 2} : Set (Polynomial ℤ))
    have hPJ : Ideal.span ({Polynomial.X} : Set (Polynomial ℤ)) ≤ J := by
      rw [Ideal.span_le]
      intro p hp
      rw [Set.mem_singleton_iff] at hp
      subst p
      exact Ideal.subset_span (by simp)
    have hxnot : Polynomial.C 2 ∉ Ideal.span ({Polynomial.X} : Set (Polynomial ℤ)) := by
      intro hx
      have hcoeff := Polynomial.X_dvd_iff.mp (Ideal.mem_span_singleton.mp hx)
      norm_num at hcoeff
    have hxmem : Polynomial.C 2 ∈ J := by
      exact Ideal.subset_span (by simp)
    have hone_mem := h.2 J (Polynomial.C 2) hPJ hxnot hxmem
    change 1 ∈ Ideal.span ({Polynomial.X, Polynomial.C 2} : Set (Polynomial ℤ)) at hone_mem
    rw [Ideal.mem_span_pair] at hone_mem
    obtain ⟨a, b, hab⟩ := hone_mem
    have hcoeff := congrArg (fun p : Polynomial ℤ => p.coeff 0) hab
    simp at hcoeff
    have hdiv : (2 : ℤ) ∣ 1 := ⟨b.coeff 0, by simpa [mul_comm] using hcoeff.symm⟩
    norm_num at hdiv


theorem q8_nonzero_prime_in_pid_is_maximal {R : Type*} [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R] (P : Ideal R) (hP : P.IsPrime) (hP0 : P ≠ ⊥) : P.IsMaximal := by
  rw [Ideal.isMaximal_iff]
  refine ⟨?_, ?_⟩
  · intro h_one_mem
    exact hP.ne_top ((Ideal.eq_top_iff_one P).mpr h_one_mem)
  · intro Q x hPQ hx_not_mem_P hx_mem_Q
    -- Write both ideals with generators.  From `p = qk`, primality of `(p)` says that either
    -- `q` already lies in `(p)` or `k` does; the first contradicts strictness and the second
    -- makes `q` a unit.
    obtain ⟨p, rfl⟩ := IsPrincipalIdealRing.principal P
    obtain ⟨q, rfl⟩ := IsPrincipalIdealRing.principal Q
    have hp_ne_zero : p ≠ 0 := by
      intro hp_zero
      apply hP0
      simp [hp_zero]
    have hp_mem : p ∈ Ideal.span ({p} : Set R) := Ideal.subset_span (Set.mem_singleton p)
    obtain ⟨k, hp_eq_qk⟩ : ∃ k : R, p = q * k :=
      Ideal.mem_span_singleton.mp (hPQ hp_mem)
    have hqk_mem : q * k ∈ Ideal.span ({p} : Set R) := by
      rw [← hp_eq_qk]
      exact hp_mem
    rcases hP.mem_or_mem hqk_mem with hq_mem | hk_mem
    · have hQ_le_P : Ideal.span ({q} : Set R) ≤ Ideal.span ({p} : Set R) := by
        apply Ideal.span_le.2
        rintro y hy
        rcases Set.mem_singleton_iff.mp hy with rfl
        exact hq_mem
      exact (hx_not_mem_P (hQ_le_P hx_mem_Q)).elim
    · obtain ⟨l, hk_eq_pl⟩ : ∃ l : R, k = p * l :=
        Ideal.mem_span_singleton.mp hk_mem
      have hq_mul_l : q * l = 1 := by
        apply mul_left_cancel₀ hp_ne_zero
        calc
          p * (q * l) = q * (p * l) := by ring
          _ = q * k := by rw [hk_eq_pl]
          _ = p := hp_eq_qk.symm
          _ = p * 1 := (mul_one p).symm
      exact Ideal.mem_span_singleton.mpr ⟨l, hq_mul_l.symm⟩


theorem q9_prime_ideals_maximal {R : Type*} [CommRing R]
    (hpower : ∀ x : R, ∃ n : ℕ, 1 < n ∧ x ^ n = x) (P : Ideal R) (hP : P.IsPrime) :
    P.IsMaximal := by
  rw [Ideal.isMaximal_iff]
  refine ⟨fun hone_mem => hP.ne_top ((Ideal.eq_top_iff_one P).mpr hone_mem), ?_⟩
  intro J x hPJ hxP hxJ
  obtain ⟨n, hn, hnx⟩ := hpower x
  have hn0 : 0 < n := lt_trans zero_lt_one hn
  have hnk : n - 1 + 1 = n := Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr (Nat.ne_of_gt hn0))
  have hprod : x * (x ^ (n - 1) - 1) ∈ P := by
    -- The power relation factors as `x (x^(n-1) - 1) = 0`.
    have hzero : x * (x ^ (n - 1) - 1) = 0 := by
      calc
        x * (x ^ (n - 1) - 1) = x ^ (n - 1 + 1) - x := by
          rw [pow_succ]
          ring
        _ = 0 := by rw [hnk, hnx, sub_self]
    rw [hzero]
    exact P.zero_mem
  rcases hP.mem_or_mem hprod with hx | hx
  · exact (hxP hx).elim
  · have hxpow : x ^ (n - 1) ∈ J :=
      J.pow_mem_of_mem hxJ _ (Nat.sub_pos_of_lt hn)
    have hxsub : x ^ (n - 1) - 1 ∈ J := hPJ hx
    have hone_mem : (1 : R) ∈ J := by
      have hdifference : x ^ (n - 1) - (x ^ (n - 1) - 1) ∈ J := J.sub_mem hxpow hxsub
      convert hdifference using 1
      ring
    exact hone_mem


theorem q10_top_product_ideal_not_prime :
    ¬ (Ideal.prod (⊤ : Ideal ℤ) (⊤ : Ideal ℤ)).IsPrime := by
  intro h
  apply h.ne_top
  ext x
  simp


theorem q11_zero_product_ideal_not_prime :
    ¬ (Ideal.prod (⊥ : Ideal ℤ) (⊥ : Ideal ℤ)).IsPrime := by
  intro h
  have hprod : ((1, 0) : ℤ × ℤ) * (0, 1) ∈ Ideal.prod (⊥ : Ideal ℤ) (⊥ : Ideal ℤ) := by
    simp
  rcases h.mem_or_mem hprod with hleft | hright
  · exact one_ne_zero hleft.1
  · exact one_ne_zero hright.2


theorem q12_product_ideal_not_prime :
    ¬ (Ideal.prod (Ideal.span ({2} : Set ℤ)) (Ideal.span ({3} : Set ℤ))).IsPrime := by
  intro h
  -- The product `(2,1)(1,3)` lies in `(2) × (3)`, but neither factor does.
  have hprod : ((2, 1) : ℤ × ℤ) * (1, 3) ∈
      Ideal.prod (Ideal.span ({2} : Set ℤ)) (Ideal.span ({3} : Set ℤ)) := by
    constructor
    · exact Ideal.subset_span (by simp)
    · exact Ideal.subset_span (by simp)
  rcases h.mem_or_mem hprod with hleft | hright
  · have hthree : (3 : ℤ) ∣ 1 := Ideal.mem_span_singleton.mp hleft.2
    norm_num at hthree
  · have htwo : (2 : ℤ) ∣ 1 := Ideal.mem_span_singleton.mp hright.1
    norm_num at htwo


theorem q13_top_times_three_prime_maximal :
    (Ideal.prod (⊤ : Ideal ℤ) (Ideal.span ({3} : Set ℤ))).IsPrime ∧
      (Ideal.prod (⊤ : Ideal ℤ) (Ideal.span ({3} : Set ℤ))).IsMaximal := by
  have h3prime : (Ideal.span ({3} : Set ℤ)).IsPrime :=
    (Ideal.span_singleton_prime (p := (3 : ℤ)) (by norm_num)).mpr
      (Int.prime_iff_natAbs_prime.mpr (by norm_num))
  have h3max : (Ideal.span ({3} : Set ℤ)).IsMaximal := by
    letI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
    simpa using Int.ideal_span_isMaximal_of_prime 3
  constructor
  · letI : (Ideal.span ({3} : Set ℤ)).IsPrime := h3prime
    -- Pulling a prime ideal back along the second projection gives `ℤ × (3)`.
    exact Ideal.isPrime_ideal_prod_top'
  · have hsurj : Function.Surjective (RingHom.snd ℤ ℤ) := fun y => ⟨(0, y), rfl⟩
    letI : (Ideal.span ({3} : Set ℤ)).IsMaximal := h3max
    -- The same surjective projection pulls maximality back to the product ring.
    simpa [Ideal.prod] using
      (Ideal.comap_isMaximal_of_surjective (RingHom.snd ℤ ℤ) hsurj
        (K := Ideal.span ({3} : Set ℤ)))


theorem q14_exists_pairwise_incomparable_subfamily_covering {R : Type*} [CommRing R] {n : ℕ}
    (P : Fin n → Ideal R) :
    ∃ S : Finset (Fin n),
      (∀ i, ∃ j ∈ S, P i ≤ P j) ∧
      (∀ i ∈ S, ∀ j ∈ S, i ≠ j → ¬ P i ≤ P j) := by
  classical
  let familyValues : Finset (Ideal R) := Finset.univ.image P
  let maximalValues : Finset (Ideal R) :=
    familyValues.filter (Maximal fun Q => Q ∈ familyValues)
  have hfamilyValues : ∀ i, P i ∈ familyValues := by
    intro i
    exact Finset.mem_image.mpr ⟨i, Finset.mem_univ _, rfl⟩
  have hmaximalValues : ∀ Q, Q ∈ maximalValues ↔
      Maximal (fun Q => Q ∈ familyValues) Q := by
    intro Q
    simp only [maximalValues, Finset.mem_filter]
    constructor
    · exact fun h => h.2
    · exact fun h => ⟨h.1, h⟩
  have hrepresentativeExists : ∀ Q : maximalValues, ∃ i : Fin n, P i = Q := by
    intro Q
    obtain ⟨i, _, hi⟩ := Finset.mem_image.mp ((hmaximalValues Q).mp Q.property).1
    exact ⟨i, hi⟩
  choose representative hrepresentative using hrepresentativeExists
  let selectedIndices : Finset (Fin n) := Finset.univ.image representative
  refine ⟨selectedIndices, ?_, ?_⟩
  · intro i
    obtain ⟨Q, hiQ, hQmax⟩ := familyValues.exists_le_maximal (hfamilyValues i)
    have hQmaximal : Q ∈ maximalValues := hmaximalValues Q |>.mpr hQmax
    let q : maximalValues := ⟨Q, hQmaximal⟩
    refine ⟨representative q, Finset.mem_image.mpr ⟨q, Finset.mem_univ _, rfl⟩, ?_⟩
    rw [hrepresentative q]
    exact hiQ
  · intro i hi j hj hij hle
    obtain ⟨q, _, hqi⟩ := Finset.mem_image.mp hi
    obtain ⟨r, _, hrj⟩ := Finset.mem_image.mp hj
    have hPQ : (q : Ideal R) ≤ r := by
      rw [← hrepresentative q, ← hrepresentative r, hqi, hrj]
      exact hle
    have hrq : (r : Ideal R) ≤ q :=
      ((hmaximalValues q).mp q.property).2 ((hmaximalValues r).mp r.property).1 hPQ
    have hqr : (q : Ideal R) = r := le_antisymm hPQ hrq
    have hq_eq_r : q = r := Subtype.ext hqr
    have hij' : i = j := by
      rw [← hqi, ← hrj, hq_eq_r]
    exact hij hij'


theorem q15_exists_separating_element {R : Type*} [CommRing R] {n : ℕ}
    (I : Ideal R) (P : Fin n → Ideal R) (hP : ∀ i, (P i).IsPrime)
    (hI : ∀ i, ¬ I ≤ P i)
    (hincomparable : ∀ i j, i ≠ j → ¬ P i ≤ P j) :
    ∀ i, ∃ x : R, x ∈ I ∧ x ∉ P i ∧ ∀ j, j ≠ i → x ∈ P j := by
  classical
  intro i
  let s : Finset (Fin n) := Finset.univ.erase i
  let Q : Ideal R := s.prod P
  have hs : ∀ j ∈ s, ¬ P j ≤ P i := by
    intro j hj
    exact hincomparable j i (Finset.mem_erase.mp hj).1
  have hQ : ¬ Q ≤ P i := by
    have hprod : ∀ t : Finset (Fin n), (∀ j ∈ t, ¬ P j ≤ P i) →
        ¬ t.prod P ≤ P i := by
      intro t
      induction t using Finset.induction_on with
      | empty =>
        intro _ htop
        have htop' : (⊤ : Ideal R) ≤ P i := by simpa using htop
        exact (hP i).ne_top (top_unique htop')
      | insert j t hj ih =>
        rw [Finset.prod_insert hj]
        intro ht hmul
        rcases (hP i).mul_le.mp hmul with hji | ht_le
        · exact (ht j (Finset.mem_insert_self _ _)) hji
        · exact ih (fun k hk => ht k (Finset.mem_insert_of_mem hk)) ht_le
    exact hprod s hs
  have hIQ : ¬ I * Q ≤ P i := by
    intro hmul
    rcases (hP i).mul_le.mp hmul with hI_le | hQ_le
    · exact hI i hI_le
    · exact hQ hQ_le
  obtain ⟨x, hxIQ, hxnot⟩ := Set.not_subset.mp hIQ
  refine ⟨x, Ideal.mul_le_right hxIQ, hxnot, ?_⟩
  intro j hji
  have hjs : j ∈ s := Finset.mem_erase.mpr ⟨hji, Finset.mem_univ _⟩
  have hQj : Q ≤ P j := by
    dsimp [Q]
    rw [← Finset.prod_erase_mul _ _ hjs]
    exact Ideal.mul_le_left
  exact hQj (Ideal.mul_le_left hxIQ)


theorem q16_sum_of_separating_elements_avoids_all {R : Type*} [CommRing R] {n : ℕ}
    (I : Ideal R) (P : Fin n → Ideal R) (c : Fin n → R)
    (hcI : ∀ i, c i ∈ I)
    (hc : ∀ i, c i ∉ P i ∧ ∀ j, j ≠ i → c i ∈ P j) :
    ∃ x : R, x ∈ I ∧ ∀ i, x ∉ P i := by
  classical
  refine ⟨∑ i, c i, I.sum_mem fun i _ => hcI i, ?_⟩
  intro i hsum
  have hotherSum : ∑ j ∈ Finset.univ.erase i, c j ∈ P i := by
    apply (P i).sum_mem
    intro j hj
    exact (hc j).2 i (Finset.mem_erase.mp hj).1.symm
  have hci : c i ∈ P i := by
    rw [← Finset.sum_erase_add _ _ (Finset.mem_univ i)] at hsum
    simpa only [add_sub_cancel_left] using (P i).sub_mem hsum hotherSum
  exact (hc i).1 hci


theorem q17_prime_avoidance_of_pairwise_incomparable {R : Type*} [CommRing R] {n : ℕ}
    (I : Ideal R) (P : Fin n → Ideal R) (hP : ∀ i, (P i).IsPrime)
    (hincomparable : ∀ i j, i ≠ j → ¬ P i ≤ P j)
    (hcover : ∀ x : R, x ∈ I → ∃ i : Fin n, x ∈ P i) :
    ∃ i : Fin n, I ≤ P i := by
  by_contra hcontained
  push Not at hcontained
  choose c hcI hcnotMem hmemOther using
    q15_exists_separating_element I P hP hcontained hincomparable
  obtain ⟨x, hxI, hxnot⟩ := q16_sum_of_separating_elements_avoids_all I P c hcI
    (fun i => ⟨hcnotMem i, hmemOther i⟩)
  obtain ⟨i, hxPi⟩ := hcover x hxI
  exact hxnot i hxPi


theorem q18_prime_avoidance {R : Type*} [CommRing R] (n : ℕ) (I : Ideal R)
    (P : Fin n → Ideal R) (hP : ∀ i : Fin n, (P i).IsPrime)
    (hcover : ∀ x : R, x ∈ I → ∃ i : Fin n, x ∈ P i) : ∃ i : Fin n, I ≤ P i := by
  obtain ⟨S, hScover, hSincomparable⟩ :=
    q14_exists_pairwise_incomparable_subfamily_covering P
  let e : S ≃ Fin S.card := S.equivFin
  let Q : Fin S.card → Ideal R := fun k => P (e.symm k)
  have hQprime : ∀ k, (Q k).IsPrime := by
    intro k
    exact hP (e.symm k)
  have hQincomparable : ∀ k l, k ≠ l → ¬ Q k ≤ Q l := by
    intro k l hkl hQle
    apply hSincomparable (e.symm k) (e.symm k).property (e.symm l) (e.symm l).property
    · intro heq
      apply hkl
      calc
        k = e (e.symm k) := (e.apply_symm_apply k).symm
        _ = e (e.symm l) := congrArg e (Subtype.ext heq)
        _ = l := e.apply_symm_apply l
    · exact hQle
  have hQcover : ∀ x : R, x ∈ I → ∃ k : Fin S.card, x ∈ Q k := by
    intro x hx
    obtain ⟨i, hxi⟩ := hcover x hx
    obtain ⟨j, hjS, hij⟩ := hScover i
    refine ⟨e ⟨j, hjS⟩, ?_⟩
    change x ∈ P (e.symm (e ⟨j, hjS⟩))
    rw [e.symm_apply_apply]
    exact hij hxi
  obtain ⟨k, hIk⟩ :=
    q17_prime_avoidance_of_pairwise_incomparable I Q hQprime hQincomparable hQcover
  refine ⟨e.symm k, ?_⟩
  exact hIk

end Solutions.RingTheory.PrimeAndMaximalIdeals
