import Exercises.RingTheory.«01Rings»
import Solutions.RingTheory.«01Rings»
import Meta.BanCheck

open Meta

assert_not_uses Exercises.RingTheory.Rings.q3_char_prime_or_zero [CharP.char_is_prime_or_zero]
assert_not_uses Exercises.RingTheory.Rings.q7_unique_int_ring_hom [RingHom.ext_int]
assert_not_uses Exercises.RingTheory.Rings.q9_ring_hom_maps_units [IsUnit.map]
assert_not_uses Exercises.RingTheory.Rings.q10_one_add_square_zero_is_unit [IsNilpotent.isUnit_one_add, IsNilpotent.isUnit_add_one]
assert_not_uses Exercises.RingTheory.Rings.q11_unit_add_square_zero_is_unit [IsNilpotent.isUnit_add_left_of_commute]
assert_not_uses Exercises.RingTheory.Rings.q14_finite_domain_mul_surjective [IsLeftRegular.isUnit_of_finite]
assert_not_uses Exercises.RingTheory.Rings.q15_domain_idempotent [IsIdempotentElem.iff_eq_zero_or_one]
assert_not_uses Exercises.RingTheory.Rings.q20_gaussian_no_zero_divisors [Zsqrtd.eq_zero_or_eq_zero_of_mul_eq_zero]
assert_not_uses Exercises.RingTheory.Rings.q21_gaussian_units_exactly_four [Zsqrtd.norm_eq_one_iff']
assert_not_uses Solutions.RingTheory.Rings.q3_char_prime_or_zero [CharP.char_is_prime_or_zero]
assert_not_uses Solutions.RingTheory.Rings.q7_unique_int_ring_hom [RingHom.ext_int]
assert_not_uses Solutions.RingTheory.Rings.q9_ring_hom_maps_units [IsUnit.map]
assert_not_uses Solutions.RingTheory.Rings.q10_one_add_square_zero_is_unit [IsNilpotent.isUnit_one_add, IsNilpotent.isUnit_add_one]
assert_not_uses Solutions.RingTheory.Rings.q11_unit_add_square_zero_is_unit [IsNilpotent.isUnit_add_left_of_commute]
assert_not_uses Solutions.RingTheory.Rings.q14_finite_domain_mul_surjective [IsLeftRegular.isUnit_of_finite]
assert_not_uses Solutions.RingTheory.Rings.q15_domain_idempotent [IsIdempotentElem.iff_eq_zero_or_one]
assert_not_uses Solutions.RingTheory.Rings.q20_gaussian_no_zero_divisors [Zsqrtd.eq_zero_or_eq_zero_of_mul_eq_zero]
assert_not_uses Solutions.RingTheory.Rings.q21_gaussian_units_exactly_four [Zsqrtd.norm_eq_one_iff']
